version: '3.8'
services:
  api:
    build: ./api
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - PG_PASSWORD=student_password
      - PG_USER=student_user
      - PG_DATABASE=labo
      - PG_PORT=5432
      - PG_HOST=postgres
      - PORT=8080
  webapp:
    #image: eslih/basic-webapp:v1.0.1
    build: ./web
    command: uwsgi --ini app.ini
    ports:
      - 5000:5000
    depends_on:
      - api
  nginx:
    image: webapp-nginx
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - webapp
  postgres:
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_PASSWORD=student_password
      - POSTGRES_USER=student_user
      - POSTGRES_DB=labo
