apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkg01
  namespace: research-concept
spec:
  distribution:
    version: v1.18
  topology:
    controlPlane:
      count: 1
      class: best-effort-small
      storageClass: pacific-gold-storage-policy
    workers:
      count: 2
      class: best-effort-small
      storageClass: pacific-gold-storage-policy
  settings:
    network:
      services:
        cidrBlocks: ["10.97.0.0/24"]
      pods:
        cidrBlocks: ["10.245.0.0/21"]