apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      -
        env:
        - name: PG_DATABASE
          value: labo
        - name: PG_HOST
          value: postgres
        - name: PG_PASSWORD
          value: student_password
        - name: PG_PORT
          value: "5432"
        - name: PG_USER
          value: student_user
        image: eslih/basic-webapp-api:v1.1.0
        name: api
        resources: {}
      restartPolicy: Always