apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    # Should be recreate, otherwise another container will spin up and will request access to the volume.
    # The volume may only be attached to a single container (ReadWriteOnce).
    # By forcing a recreate the pod will be removed and then be recreated.
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:13.1-alpine
          name: postgres
          env:
            - name: POSTGRES_DB
              value: labo
            - name: POSTGRES_PASSWORD
              value: student_password
            - name: POSTGRES_USER
              value: student_user
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres
              subPath: postgres
          resources: { }
      restartPolicy: Always
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: longhorn-postgres-pvc
status: { }
