apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
     app: postgres
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: labo
        - name: POSTGRES_PASSWORD
          value: student_password
        - name: POSTGRES_USER
          value: student_user
        image: postgres:12.1-alpine
        name: postgres
        resources: {}
      restartPolicy: Always
status: {}
