apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # Name must start with longhorn-...
  name: longhorn-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi