---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # Name must start with longhorn-...
  name: longhorn-statics-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100M