apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # Name must start with longhorn-...
  name: standard-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi